/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.ListFrames;

import Domain.Controller;
import Presentation.MainPage;
import Presentation.Book.Cancellation;
import Presentation.Book.Room;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Unskipp
 */
public class ListFrames extends javax.swing.JFrame
{

    /**
     * Creates new form ListFrames
     */
    private Controller controller;
    private String frameName;

    public ListFrames()
    {
        initComponents();

    }

    public ListFrames(Controller controller, String frame)
    {
        this();
        frameName = frame;
        this.controller = controller;
        if (frame.equals("Employees"))
        {
            jTable1.setModel(controller.display(frame));
            Object o = new Object();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            o = "ID";
            model.addElement(o);
            o = "Name";
            model.addElement(o);
            o = "Position";
            model.addElement(o);
            jComboBoxType1.setModel(model);
        } else if (frame.equals("Clients"))
        {
            jTable1.setModel(controller.display(frame));
            Object o = new Object();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            o = "ID";
            model.addElement(o);
            o = "Name";
            model.addElement(o);
            jComboBoxType1.setModel(model);

        } else if (frame.equals("Facilities"))
        {
            jTable1.setModel(controller.display(frame));
            Object o = new Object();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            o = "Type";
            model.addElement(o);
            o = "Price";
            model.addElement(o);
            jComboBoxType1.setModel(model);
        } else if (frame.equals("Reservations"))
        {
            jTable1.setModel(controller.display(frame));
            Object o = new Object();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            o = "Name";
            model.addElement(o);
            o = "ID";
            model.addElement(o);
            o = "Reservation ID";
            model.addElement(o);
            jComboBoxType1.setModel(model);
        } else
        {
            jTable1.setModel(controller.display("Rooms"));
            Object o = new Object();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            o = "ID";
            model.addElement(o);
            o = "Capacity";
            model.addElement(o);
            o = "Price";
            model.addElement(o);
            jComboBoxType1.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButtonExactMatch = new javax.swing.JButton();
        jComboBoxType1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch1 = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonConfirmPayment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex,int colIndex)
            {
                return false;
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuRomms = new javax.swing.JMenuItem();
        jMenuClients = new javax.swing.JMenuItem();
        jMenuFacilities = new javax.swing.JMenuItem();
        jMenuEmployees = new javax.swing.JMenuItem();
        jMenuReservations = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonExactMatch.setText("Exact match");
        jButtonExactMatch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonExactMatchActionPerformed(evt);
            }
        });

        jComboBoxType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Search by");

        jTextFieldSearch1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTextFieldSearch1KeyReleased(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonConfirmPayment.setText("Confirm payment");
        jButtonConfirmPayment.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonConfirmPaymentActionPerformed(evt);
            }
        });

        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("HOME");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Account");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Book");

        jMenuItem1.setText("Room");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Facilities");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Cancelation");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("List");

        jMenuRomms.setText("Rooms");
        jMenuRomms.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuRommsActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuRomms);

        jMenuClients.setText("Clients");
        jMenuClients.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuClientsActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuClients);

        jMenuFacilities.setText("Facilities");
        jMenuFacilities.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuFacilitiesActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuFacilities);

        jMenuEmployees.setText("Employees");
        jMenuEmployees.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuEmployeesActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuEmployees);

        jMenuReservations.setText("Reservations");
        jMenuReservations.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuReservationsActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuReservations);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Help");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jComboBoxType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConfirmPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jButtonExactMatch)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(90, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExactMatch)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDelete)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonConfirmPayment)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu1MouseClicked
    {//GEN-HEADEREND:event_jMenu1MouseClicked
        // TODO add your handling code here:
        MainPage frame = new MainPage(controller);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Room frame = new Room(controller);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem3ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Cancellation frame = new Cancellation(controller);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuRommsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuRommsActionPerformed
    {//GEN-HEADEREND:event_jMenuRommsActionPerformed
        jTable1.setModel(controller.display("Rooms"));
        Object o = new Object();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        o = "ID";
        model.addElement(o);
        o = "Capacity";
        model.addElement(o);
        o = "Price";
        model.addElement(o);
        jComboBoxType1.setModel(model);
        frameName = "Rooms";
    }//GEN-LAST:event_jMenuRommsActionPerformed

    private void jMenuClientsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuClientsActionPerformed
    {//GEN-HEADEREND:event_jMenuClientsActionPerformed
        jTable1.setModel(controller.display("Clients"));
        Object o = new Object();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        o = "ID";
        model.addElement(o);
        o = "Name";
        model.addElement(o);
        jComboBoxType1.setModel(model);
        frameName = "Clients";
    }//GEN-LAST:event_jMenuClientsActionPerformed

    private void jMenuFacilitiesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuFacilitiesActionPerformed
    {//GEN-HEADEREND:event_jMenuFacilitiesActionPerformed
        jTable1.setModel(controller.display("Facilities"));
        Object o = new Object();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        o = "Type";
        model.addElement(o);
        o = "Price";
        model.addElement(o);
        jComboBoxType1.setModel(model);
        frameName = "Facilities";
    }//GEN-LAST:event_jMenuFacilitiesActionPerformed

    private void jMenuEmployeesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuEmployeesActionPerformed
    {//GEN-HEADEREND:event_jMenuEmployeesActionPerformed
        jTable1.setModel(controller.display("Employees"));
        Object o = new Object();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        o = "ID";
        model.addElement(o);
        o = "Name";
        model.addElement(o);
        o = "Position";
        model.addElement(o);
        jComboBoxType1.setModel(model);
        frameName = "Employees";
    }//GEN-LAST:event_jMenuEmployeesActionPerformed

    private void jMenuReservationsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuReservationsActionPerformed
    {//GEN-HEADEREND:event_jMenuReservationsActionPerformed
        jTable1.setModel(controller.display("Reservations"));
        Object o = new Object();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        o = "Name";
        model.addElement(o);
        o = "ID";
        model.addElement(o);
        o = "Reservation ID";
        model.addElement(o);
        jComboBoxType1.setModel(model);
        frameName = "Reservations";
    }//GEN-LAST:event_jMenuReservationsActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteActionPerformed
        if (jTable1.getSelectedRow() == -1)
        {
            jLabel1.setText("you have to select a reservation from the list!");
        } else
        {
            System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            if (controller.delete("reservation", jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()))
            {
                jTable1.setModel(controller.display("Reservations"));
                jLabel1.setText("reservation successfully deleted");
            } else
            {
                jLabel1.setText("failed to delete reservation");
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonConfirmPaymentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConfirmPaymentActionPerformed
    {//GEN-HEADEREND:event_jButtonConfirmPaymentActionPerformed
//        if (jTable1.getSelectedIndex() == -1)
//        {
//            jLabel1.setText("you have to select a reservation from the list!");
//        } else
//        {
//            double amount = -1;
//            while (amount < 0)
//            {
//                try
//                {
//                    amount = Double.parseDouble(JOptionPane.showInputDialog("Select amount:"));
//                } catch (java.lang.NumberFormatException ex)
//                {
//                    System.out.println(ex.getMessage());
//                }
//            }
//            if (controller.confirmPayment(amount, jTable1.getSelectedIndex()))
//            {
//                jLabel1.setText("payment confirmed");
//            } else
//            {
//                jLabel1.setText("payment was not confirmed");
//            }
//        }
    }//GEN-LAST:event_jButtonConfirmPaymentActionPerformed

    private void jTextFieldSearch1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldSearch1KeyReleased
    {//GEN-HEADEREND:event_jTextFieldSearch1KeyReleased
        // TODO add your handling code here:
        String valueOfSearch = jTextFieldSearch1.getText();
        if (!"".equals(valueOfSearch) && valueOfSearch != null)
        {
            jTable1.setModel(controller.searchBy(valueOfSearch, jComboBoxType1.getSelectedItem(), frameName));
        } else
        {
            jTable1.setModel(controller.display(frameName));
        }
    }//GEN-LAST:event_jTextFieldSearch1KeyReleased

    private void jButtonExactMatchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonExactMatchActionPerformed
    {//GEN-HEADEREND:event_jButtonExactMatchActionPerformed
        // TODO add your handling code here:
        String valueOfSearch = jTextFieldSearch1.getText();
        if (!"".equals(valueOfSearch) && valueOfSearch != null)
        {
            jTable1.setModel(controller.searchByExactMatch(valueOfSearch, jComboBoxType1.getSelectedItem(), frameName));
        }
        else jTable1.setModel(controller.display(frameName));
    }//GEN-LAST:event_jButtonExactMatchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1MouseClicked
    {//GEN-HEADEREND:event_jTable1MouseClicked
        // TODO add your handling code here:
        System.out.println(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn()).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ListFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ListFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ListFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ListFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ListFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmPayment;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonExactMatch;
    private javax.swing.JComboBox jComboBoxType1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClients;
    private javax.swing.JMenuItem jMenuEmployees;
    private javax.swing.JMenuItem jMenuFacilities;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuReservations;
    private javax.swing.JMenuItem jMenuRomms;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSearch1;
    // End of variables declaration//GEN-END:variables
}
